compare_conf/urls.py
from django.conf.urls import url
from compare_conf import views

app_name = 'compare_cluster'

urlpatterns = [
    url(r'^lists/$',views.cluster_list,name='home'),
    url(r'^compare/',views.compare_cluster,name='compare'),
    url(r'^user/',views.cluster_name,name='cluster_name'),
]

hadoop_monitor/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from compare_conf import views

urlpatterns = [
    url(r'^$', views.cluster_list,name='cluster'),
    url(r'^compare_cluster/',include('compare_conf.urls')),
    url(r'^admin/', admin.site.urls),
]

compare_conf/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class test(models.Model):
    env_name = models.CharField(max_length=32)
    display_name = models.CharField(max_length=32)
    url_link = models.URLField(unique=True)

    def __str__(self):
        return self.env_name

compare_conf/forms.py
from django import forms
from compare_conf.models import test

CLUSTER_CHOICES= [
    ('Radial_prod', 'RDL_PRD'),
    ('Radial_DR', 'RDL_DR'),
    ]
#CLUSTER_CHOICES = []
#for i in test.objects.order_by('env_name'):
#    CLUSTER_CHOICES.append(i.env_name)
class FormName(forms.Form):
    Cluster_First = forms.CharField(widget=forms.Select(choices=CLUSTER_CHOICES))
    Cluser_Second = forms.CharField(widget=forms.Select(choices=CLUSTER_CHOICES))

#class FormName(forms.Form):
#    name = forms.CharField()
#    email = forms.EmailField()
#    text = forms.CharField(widget=forms.Textarea)

compare_conf/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
#from django.http import HttpResponse
from . import forms
from compare_conf.models import test
# Create your views here.
def cluster_list(request):
    return render (request,'compare_cluster/cluster.html')


def compare_cluster(request):
    form = forms.FormName()
    return render(request,'compare_cluster/forms.html',{'form':form})

def cluster_name(request):
    env_name = test.objects.order_by('env_name')
    env_dict = {'Env_name':env_name}
    return render(request,'compare_cluster/register.html',context=env_dict)
#    url_link = Clusters.objects.order_by('url_link')

templates/compare_cluster/cluster.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>DWS Supported cluster</title>
  </head>
  <body>
    
    <link rel="stylesheet" href={% static "/css/master.css" %}>
    <h1>This are cluster managed by DWS</h1>
    <a href="{% url 'compare_cluster:compare'%}">compare cluster</a>
    <a href="{% url 'compare_cluster:home'%}">home</a>

    <div id="content">
      <img src="{% static "images/barclays.png" %}" alt="Oh Oooops" class="ribbon"/>
    </div>
  </body>
</html>

templates/compare_cluster/forms.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Compare Clusters</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <link rel="stylesheet" href={% static "/css/master.css" %}>
  </head>
  <body>
    <h1>This is a Page for Cluster config comparision</h1>
    <nav class='navbar navbar-default navbar-static-top'>
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand"  href="{% url 'compare_cluster:cluster_name' %}">list clusters</a></li>
          <li><a class="navbar-link" href="{% url 'compare_cluster:home' %}">Home</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
      </form>
    </div>
  </body>
</html>

templates/compare_cluster/register.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>user info</title>
    
    <link rel="stylesheet" href={% static "/css/master.css" %}>
  </head>
  <body>
    <h1> This is list of cluster</h1>
    <div class="navbar-header">
        <a href="{% url 'compare_cluster:home'%}">home</a>
        <a href="{% url 'compare_cluster:compare'%}">compare cluster</a>
    </div>

     {% if Env_name %}
      <div class="container">

      {% for clus in Env_name %}
      <ul>
        <li> Environment : {{ clus.env_name }}</li>
      </ul>
      {% endfor %}
    </div>
      {% endif %}
</html>